services:
  app:
    build: .
    ports:
      - "3000:3000" # Mapea el puerto interno del contenedor al externo
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: npm run dev
